---
title: "Worksheet_3b"
author: "Jason Lloyd C. Mijares"
date: "2024-10-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## No. 1

```{r}

## a.

Census <- data.frame(
  Respondents = c(1:20),
  Sex = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2, 2, 1,2),
  Fathers_Occupation = c(1, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 3, 1, 2, 1),
  PersonsAtHome = c(5, 7, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 8, 8, 3, 11, 7, 6),
  SiblingsAtSchool = c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2),
  TypesOfHouses = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
)

Census
```
```{r}
## b.

## Describe the data. 
## It contains information about 20 respondents with 6 variables: Respondents, Sex, Fathers Occupataion,
## Persons at Home, Siblings at school, Types of houses
 
str(Census)
summary(Census)
```

```{r}
## c.

siblingMean <- mean(Census$SiblingsAtSchool)

siblingMean

## Is the mean number of siblings attending is 5? No, it is 2.95

```
```{r}
## d. 

subset_Census1To2 <- subset(Census, Respondents <= 2)

subset_Census1To2
```

```{r}
## e.

Census3and5 <- Census[c(3,5),c(2,4)]

Census3and5
```
```{r}
## f.

types_houses <- Census$TypesOfHouses

types_houses
```
```{r}
## g.

male_farmer <- Census[Census$Sex == 1 & Census$Fathers_Occupation,]

male_farmer
```
```{r}
## h.

female_siblings <- Census[Census$Sex == 2 & Census$SiblingsAtSchool >=5,]

female_siblings
```
## No. 2
```{r}
df = data.frame(Ints=integer(), Doubles=double(), Characters=character(), Logicals=logical(), Factors=factor(), stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))
```
```{r}
## a.

## The result describes and empty data frame with 0 observations and 5 variables. 
## Every variable has a specific type also.
```
## No. 3
```{r}
## a. 

householdData <- read.csv("HouseholdData.csv")
householdData
```

```{r}
## b.

householdData$Sex <- factor(householdData$Sex, levels = c("Male","Female"), labels = c(1,2))

householdData$Sex <-as.integer(householdData$Sex)

householdData

```

```{r}
##  c.

householdData$Types_of_Houses <- factor(householdData$Types_of_Houses, levels = c("Wood", "Congrete", "Semi-Congrete"), labels = c(1,2,3))

householdData$Types_of_Houses <- as.integer(householdData$Types_of_Houses)

householdData
```

```{r}
## d.

householdData$Fathers_Occupatio <- factor(householdData$Fathers_Occupation, levels = c(1, 2, 3), labels = c("Farmer", "Driver", "Others"))

householdData
```
```{r}
## e.
femaleDriverFather <- householdData[householdData$Sex == 2 & householdData$Fathers_Occupation == 2,]

femaleDriverFather
```
```{r}
## f.

householdFemaleAndFather <- householdData[householdData$Siblings_at_School >= 5,]

householdFemaleAndFather
```
## No. 4

```{r}
## The bar chart visualizes Sentiments Of Tweets per day, with the legends:
## Negative(Red), Neutral(Orange), Positive(Blue).

## Negative sentiment is the highest among the three sentiments, 
## showing that a lot of tweets has a negative tone,
## and it has the highest tweet counts. Peaks occur on July 15 and July 21 indicating 
## increased activity during these days are significant.

## Positive sentiments is second to negative sentiment in terms of its count ## and maintains a moderate level throughout the days.

## Neutral sentiment is the lowest, meaning that tweets in this category is minimal.

## Overall, the graph shows that most tweets are composed of negative sentiments, 
## followed by positive, with neutral sentiments being the least frequent.

## It also suggests that users may tend to express more negative sentiments compared to positive ones.


```

