---
title: "Worksheet_1"
author: "Jason Lloyd C. Mijares"
date: "2024-09-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## No.1

```{r}
## a. How many data points? 34

## b. Write the R code and its output.
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51, 35, 24, 33, 41)

length(age)
```
## No.2

```{r}
age_reciprocal <- 1/age

print(age_reciprocal)
```

## No.3
```{r}
new_age <- c(age, 0, age)

## What happen to the new_age?
## it combined the elements of age, 0, age chronologically that resulted to new_age(vector) having elements of 69
```


## No. 4
```{r}
sort(age)
```
## No. 5
```{r}
min(age)
max(age)
```
## No. 6

```{r}
## a & b
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)

length(data)

## a. How many data points? 12
```

## No. 7
```{r}
new_vector <- data*2

print(new_vector)

```
## No. 8
```{r}
```
## 8.1

```{r}
int1_100 <- seq(1,100)

print(int1_100)
```

## 8.2
```{r}
Num20_60 <- seq(20,60)

print(Num20_60)
```
## 8.3
```{r}
mean(Num20_60)
```
## 8.4
```{r}
Num51_91 <- seq(51,91)

sum(Num51_91)
```
## 8.5 
```{r}
int1_1000 <- seq(1,1000)

print(int1_1000)
```


```{r}
## a. & b
F8.1 <- length(int1_100)
F8.2 <- length(Num20_60)
F8.3 <- length(Num20_60)
F8.4 <- length(Num51_91)

total_length <- F8.1 + F8.2 + F8.3 + F8.4

print(total_length)

## c.
int1_10 <- int1_1000[int1_1000 <= 10]
new_max <- max(int1_10)
print(new_max)

```

## No.9
```{r}
Filter(function(i){ all(i %% c(3,5,7) != 0)}, seq(100))
```
## No.10
```{r}
seq_1_100 <- seq(100,1)

print(seq_1_100)
```
## No. 11
```{r}
result <- Filter(function(i) { (i %% 3==0 || i %% 5 == 0) }, seq(1,25))

print(result)

```

```{r}
## a. & b
i10 <- length(seq_1_100)
i11 <- length(result)

total_length1 <- i10 + i11

print(total_length1)


```
## No.12
```{r}

# x <- {0 + x + 5 + }

## An error occured 

```
## No.13
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)

print(score[2])
print(score[3])
```
## No.14
```{r}
a = c(1,2,NA,4,NA,6,7)
print(a,na.print="-999")
## The code changed the na into -999
```
## No. 15
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)
```
