---
title: "Rworksheet_Mijares#4a"
author: "Jason Lloyd C. Mijares"
date: "2024-10-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## No. 1

```{r}
Shoes <- data.frame(
  Shoe_size = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0), Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0), Gender = c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M"))

Shoes
```

```{r}
## a. The data frame consists of different Shoe Size, Height, and Genders.
```

```{r}

## b. 

M_subset <- subset(Shoes, Gender == "M", select = c(Shoe_size, Height))

M_subset
```

```{r}
F_subset <- subset(Shoes, Gender == "F", select = c(Shoe_size, Height))

F_subset 
```
## c.

```{r}
mean(Shoes$Shoe_size)
```
```{r}
mean(Shoes$Height) 
```
## d.

`
The taller you are the bigger the shoe size
`

## No. 2

```{r}
months_vector <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", " November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")

factor_months_vector <- factor(months_vector)

factor_months_vector

```
## No. 3

```{r}
summary(months_vector)
```
```{r}
summary(factor_months_vector)
```
`
No. factor_months_vector is more useful than months_vector because it precisely factors each month
`
## No. 4

```{r}
directions <- c("East", "West", "North")

freq <- c(1,4,3)

factor_data <- rep(directions,freq)

new_order_data <- factor(factor_data, levels = c("East","West","North"), ordered = TRUE)

new_order_data
```
## No. 5

```{r}
## a.b

file <- "import_march.csv"


data <- read.table(file, header = TRUE, sep = ",", stringsAsFactors = FALSE)

# Print the imported data
print(data)

```
## No. 6

```{r}

## user_input = as.numeric(readline(prompt = "Enter a random number from 1 to 50: "))

user_input <- 20

if(user_input == 20){
  print(TRUE)
}else if(user_input >= 1 && user_input <= 50){
  print(user_input)
}else{
  print("The number selected is beyond the range of 1 to 50")
}
```
## No. 7

```{r}

min_bills <-function(snackPrice){
 bills <- c(1000, 500, 200, 100, 50)


num_bills <- 0

for(bill in bills){
  count <- snackPrice %/% bill
  
  snackPrice <- snackPrice %% bill
  
  num_bills <- num_bills + count
}

return(num_bills)
}

## snackPrice <- as.numeric(readline(prompt = "Enter the price of the snack you purchased (Must be divisible by 50: "))

snackPrice <- 1500
min_bills_needed <- min_bills(snackPrice)

print(paste("The minimum number of bills needed to pay is ", min_bills_needed))
```

## No. 8

```{r}

## a.

Grade_1stsem <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"), Grade1 = c(85, 65, 75, 95), Grade2 = c(65, 75, 55, 75), Grade3 = c(85, 90, 80, 100), Grade4 = c(100, 90, 85, 90)
)

Grade_1stsem
```

```{r}

## b.

Grade_1stsem$Average <- (Grade_1stsem$Grade1 + Grade_1stsem$Grade2 +
                          Grade_1stsem$Grade3 + Grade_1stsem$Grade4) / 4

for (i in 1:nrow(Grade_1stsem)) {
  student_name <- Grade_1stsem$Name[i]
  student_average <- Grade_1stsem$Average[i]
  result1 <- paste(student_name, "’s average grade this semester is", round(student_average, 2), ".")
  print(result1)
}

## There is no student that got an average that is over 90 points in the 1st semester
```

```{r}

## c.

total_scores <- colSums(Grade_1stsem[, 2:5])

num_students <- nrow(Grade_1stsem)
average_scores <- total_scores / num_students

difficult_tests <- average_scores < 80

if (any(difficult_tests)) {
  result2 <- paste("Test", which(difficult_tests), "was difficult.")
  print(result2)
}

```

```{r}

## d.

for (i in 1:nrow(Grade_1stsem)) {
  
  scores <- Grade_1stsem[i, 2:5] 
  highest_score <- scores[1]  

 
  for (score in scores) {
    if (score > highest_score) {
      highest_score <- score
    }
  }

 
  if (highest_score > 90) {
     print(paste(Grade_1stsem$Name[i], "’s highest grade this semester is", highest_score))
    
  }
}
```




